### PR TITLE
Add a link to the presentation

### PR DESCRIPTION
**Pull request by shivanshc**

### CODE REVIEW

**Comment by xldrx** [comment]
Do you have any objection hosting the presentation file in the repo?

**Comment by shivanshc** [comment]
> 
> 
> Do you have any objection hosting the presentation file in the repo?

Which folder in the repo should I add the presentation too?

**Comment by xldrx** [comment]
I have created a folder `presentations` in the root.

**Comment by xldrx** [comment]
Also, could you please put the full citation of the paper in the article. Something that reads, in this post we are discussing AA, BB, "xxxx", CC 2017.

**Pull request merged**
