### PR TITLE
add hckuo2 post

### PR DESCRIPTION
**Pull request by hckuo**

### CODE REVIEW

**Comment by xldrx** [comment]
Could you please put your presentation to `/presentation` folder and add a link to it in the article?

**Comment by xldrx** [comment]
Also, could you please put the full citation of the paper in the article. Something that reads, in this post we are discussing AA, BB, "xxxx", CC 2017.

**Comment by xldrx** [comment]
Optionally, there is a disconnect between the problem statement and the solution, could you elaborate both problem and the solution.

**Comment by hckuo** [comment]
done

**Pull request merged**
